### ISSUE TITLE
Error: Could not find the following rules specified in the configuration: no-trailing-comma

### ISSUE THREAD

**Issue by nabinkumarn** [rogerpadilla/angular2-minimalist-starter#17]
````
npm start

> angular2-minimalist-starter@0.0.0 start D:\OfficeWorks\angularjs\angular2-minimalist-starter
> gulp serve --env dev

[10:55:02] Requiring external module ts-node/register
[10:55:08] Using gulpfile D:\OfficeWorks\angularjs\angular2-minimalist-starter\gulpfile.ts
[10:55:08] Starting 'serve'...
[10:55:08] Starting 'dist.clean'...
[10:55:08] Finished 'dist.clean' after 21 ms
[10:55:08] Starting 'build.watch'...
[10:55:08] Starting 'font.build'...
[10:55:08] Starting 'jslib.build'...
[10:55:08] Finished 'jslib.build' after 12 ms
[10:55:08] Starting 'jslib.watch'...
[10:55:08] Finished 'jslib.watch' after 26 ms
[10:55:08] Starting 'css.build'...
[10:55:08] Starting 'tpl.build'...
[10:55:08] Starting 'tslint'...
[10:55:08] Starting 'ts.build'...

D:\OfficeWorks\angularjs\angular2-minimalist-starter\node_modules\tslint\lib\ruleLoader.js:29
        throw new Error(errorMessage);
              ^
Error: Could not find the following rules specified in the configuration:
no-trailing-comma
quotemar
    at Object.loadRules (D:\OfficeWorks\angularjs\angular2-minimalist-starter\node_modules\tslint\lib\ruleLoader.js:29:15)
    at Linter.lint (D:\OfficeWorks\angularjs\angular2-minimalist-starter\node_modules\tslint\lib\tslint.js:24:44)
    at D:\OfficeWorks\angularjs\angular2-minimalist-starter\node_modules\gulp-tslint\index.js:96:34
    at respond (D:\OfficeWorks\angularjs\angular2-minimalist-starter\node_modules\rcloader\index.js:73:7)
    at respond (D:\OfficeWorks\angularjs\angular2-minimalist-starter\node_modules\rcfinder\index.js:140:7)
    at D:\OfficeWorks\angularjs\angular2-minimalist-starter\node_modules\rcfinder\index.js:124:17
    at D:\OfficeWorks\angularjs\angular2-minimalist-starter\node_modules\rcfinder\index.js:77:13
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-minimalist-starter@0.0.0 start: `gulp serve --env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-minimalist-starter@0.0.0 start script 'gulp serve --env dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-minimalist-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-minimalist-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-minimalist-starter
npm ERR! There is likely additional logging output above.`
```

**Comment by rogerpadilla** [comment]
Fixed in latest version.
