### ISSUE TITLE
After npm start I got an error message in console

### ISSUE THREAD

**Issue by tscislo** [rogerpadilla/angular2-minimalist-starter#7]
EXCEPTION: Unexpected directive value 'undefined' on the View of component 'App'
:8080/lib/angular2/src/dom/browser_adapter.js:72 STACKTRACE:
:8080/lib/angular2/src/dom/browser_adapter.js:72 Error: Unexpected directive value 'undefined' on the View of component 'App'
    at new BaseException (http://localhost:8080/lib/angular2/src/facade/lang.js:23:23)
    at Compiler._compile (http://localhost:8080/lib/angular2/src/core/compiler/compiler.js:171:23)
    at http://localhost:8080/lib/angular2/src/core/compiler/compiler.js:223:44
    at Array.forEach (native)
    at http://localhost:8080/lib/angular2/src/core/compiler/compiler.js:206:18
    at Array.forEach (native)
    at Compiler._compileNestedProtoViews (http://localhost:8080/lib/angular2/src/core/compiler/compiler.js:204:23)
    at http://localhost:8080/lib/angular2/src/core/compiler/compiler.js:139:34
    at Zone.run (http://localhost:8080/lib/zone.js:113:17)
    at Zone.run (http://localhost:8080/lib/angular2/src/core/zone/ng_zone.js:165:42)
:8080/lib/angular2/src/dom/browser_adapter.js:75 EXCEPTION: TypeError: Cannot read property 'ref' of undefined
:8080/lib/angular2/src/dom/browser_adapter.js:72 STACKTRACE:
:8080/lib/angular2/src/dom/browser_adapter.js:72 TypeError: Cannot read property 'ref' of undefined
    at :8080/lib/angular2/src/core/compiler/compiler.js:148
    at Zone.run (zone.js:113)
    at Zone.run (:8080/lib/angular2/src/core/zone/ng_zone.js:165)
    at zoneBoundFn (zone.js:86)
:8080/lib/angular2/src/dom/browser_adapter.js:75 EXCEPTION: TypeError: Cannot read property 'elementBinders' of null
:8080/lib/angular2/src/dom/browser_adapter.js:72 STACKTRACE:
:8080/lib/angular2/src/dom/browser_adapter.js:72 TypeError: Cannot read property 'elementBinders' of null
    at AppViewManager.createRootHostView (:8080/lib/angular2/src/core/compiler/view_manager.js:151)
    at :8080/lib/angular2/src/core/compiler/dynamic_component_loader.js:112
    at Zone.run (zone.js:113)
    at Zone.run (:8080/lib/angular2/src/core/zone/ng_zone.js:165)
    at zoneBoundFn (zone.js:86)
:8080/lib/angular2/src/dom/browser_adapter.js:75 EXCEPTION: TypeError: Cannot read property 'location' of undefined
:8080/lib/angular2/src/dom/browser_adapter.js:72 STACKTRACE:
:8080/lib/angular2/src/dom/browser_adapter.js:72 TypeError: Cannot read property 'location' of undefined
    at :8080/lib/angular2/src/core/application_common.js:66
    at Zone.run (zone.js:113)
    at Zone.run (:8080/lib/angular2/src/core/zone/ng_zone.js:165)
    at zoneBoundFn (zone.js:86)
:8080/lib/angular2/src/dom/browser_adapter.js:75 EXCEPTION: TypeError: Cannot read property 'hostView' of undefined
:8080/lib/angular2/src/dom/browser_adapter.js:72 STACKTRACE:
:8080/lib/angular2/src/dom/browser_adapter.js:72 TypeError: Cannot read property 'hostView' of undefined
    at tick (:8080/lib/angular2/src/core/application_common.js:262)
    at Zone.run (zone.js:113)
    at Zone.run (:8080/lib/angular2/src/core/zone/ng_zone.js:165)
    at zoneBoundFn (zone.js:86)

Can you help me solve this issue?

**Comment by lamecoder** [comment]
removed coreDirectives to get rid of this error, but then started getting below, hope the maintainer is working on fixing it

EXCEPTION: No provider for Router! (RouterLink -> Router)
browser_adapter.js:72STACKTRACE:
browser_adapter.js:72Error: DI Exception
    at NoBindingError.BaseException [as constructor] (lang.js:23)
    at NoBindingError.AbstractBindingError [as constructor] (exceptions.js:38)
    at new NoBindingError (exceptions.js:65)
    at Injector._throwOrNull (injector.js:680)
    at Injector._getByKeyDefault (injector.js:727)
    at Injector._getByKey (injector.js:672)
    at Injector._getByDependency (injector.js:658)
    at Injector._instantiate (injector.js:550)
    at Injector._new (injector.js:542)
    at InjectorInlineStrategy.instantiateBinding (injector.js:186)
browser_adapter.js:72ERROR CONTEXT:
browser_adapter.js:72_Context {element: a.ng-binding, componentElement: app, injector: Injector}componentElement: appelement: a.ng-bindinginjector: Injector__proto__: _Context
browser_adapter.js:75EXCEPTION: TypeError: Cannot read property 'location' of undefined
browser_adapter.js:72STACKTRACE:
browser_adapter.js:72TypeError: Cannot read property 'location' of undefined
    at application_common.js:66
    at Zone.run (zone.js:113)
    at Zone.NgZone._createInnerZone.zone.fork.fork.$run [as run] (ng_zone.js:165)
    at zoneBoundFn (zone.js:86)
browser_adapter.js:75EXCEPTION: TypeError: Cannot read property 'hostView' of undefined
browser_adapter.js:72STACKTRACE:
browser_adapter.js:72TypeError: Cannot read property 'hostView' of undefined
    at zone.run.tick (application_common.js:262)
    at Zone.run (zone.js:113)
    at Zone.NgZone._createInnerZone.zone.fork.fork.$run [as run] (ng_zone.js:165)
    at zoneBoundFn (zone.js:86)

**Comment by flyingzl** [comment]
You can see my pull request or visit [my folks](https://github.com/rogerpadilla/angular2-minimalist-starter). I have been upgraded it to the latestt version.

**Comment by rogerpadilla** [comment]
Fixed in the last upgrade to Angular.37alpha
